GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/6361b61f2645a7876a415cae

###

GET http://localhost:3001/api/persons/6

###

GET http://localhost:3001/api/persons/6361b61f2645a7876a415caf

###

DELETE http://localhost:3001/api/persons/6361b9308f4389df5d9d6328

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Mateo",
    "number": "0958773947"
}