GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/63596a1e4d800e1e4be84db6

###

DELETE http://localhost:3001/api/persons/4

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Miguel",
    "number": "0999"
}